apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: iter8-cicd-pipelinerun-
spec:
  pipelineRef:
    name: kaniko-pipeline
  resources:
  - name: source
    resourceRef:
      name: iter8-git
  params:
  - name: IMAGE
    value: haih/helloworld:tekton
  - name: CONTEXT
    value: samples/cicd/app
