apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: gitops-exp
spec:
  # target identifies the service under experimentation using its fully qualified name
  target: default/productpage
  strategy:
    # this experiment will perform an A/B test
    testingPattern: A/B
    # this experiment will progressively shift traffic to the winning version
    deploymentPattern: Progressive
    actions:
      # when the experiment completes, promote the winning version using kubectl apply
      finish:
      - task: common/exec
        with:
          cmd: /bin/bash
          args: [ 
                 "-c",
                 "apt-get install -y git jq;\
                  mkdir ~/.ssh;\
                  kubectl -n {{ .namespace }} get secret iter8-key -o json | jq -r .data.id_iter8_rsa | base64 -d > ~/.ssh/id_iter8_rsa;\
                  chmod 400 ~/.ssh/id_iter8_rsa;\
                  printf \"Host github.com\n  HostName github.com\n IdentityFile ~/.ssh/id_iter8_rsa\n  StrictHostKeyChecking no\n\" > ~/.ssh/config;\
                  git config --global user.email 'iter8@iter8.tools';\
                  git config --global user.name 'Mr. Iter8';\
                  git clone git@github.com:huang195/iter8.git -b gitops;\
                  cd iter8;\
                  sed 's/candidate/stable/g' {{ .filepath }} > samples/gitops/productpage.yaml;\
                  if [ `git status -s | wc -l` != 0 ];\
                  then \
                    git checkout -b iter8_exp;\
                    git commit -a -m 'update baseline';\
                    git push -f origin iter8_exp;\
                  fi;\
                  kubectl -n {{ .namespace }} apply -f samples/gitops/istio-vs.yaml;\
                 "
                ]
  criteria:
    rewards:
    # (business) reward metric to optimize in this experiment
    - metric: default/user-engagement 
      preferredDirection: High
    objectives: # used for validating versions
    - metric: default/mean-latency
      upperLimit: 300
    requestCount: default/request-count
  duration: # product of fields determines length of the experiment
    intervalSeconds: 5
    iterationsPerLoop: 1
  versionInfo:
    # information about the app versions used in this experiment
    baseline:
      name: productpage-stable
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: samples/gitops/productpage.yaml
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: default
        name: bookinfo
        fieldPath: .spec.http[0].route[0].weight
    candidates:
    - name: productpage-candidate
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: samples/gitops/productpage-candidate.yaml
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: default
        name: bookinfo
        fieldPath: .spec.http[0].route[1].weight
