apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: is-build-needed
  annotations:
    tekton.dev/displayName: "Test if building new image is needed"
spec:
  description: >-
    This task tests if building a new image is needed

  resources:
    inputs:
    - name: source
      type: git
      description: Holds git repo
  params:
  - name: CONTEXT
    description: Relative directory path to Dockerfile
  results:
  - name: needed
    description: If a new build is needed

  steps:
  - name: check
    workingDir: $(resources.inputs.source.path)
    image: alpine/git:latest
    script: |
      #!/usr/bin/env sh
      if [ `git diff --name-only HEAD~ | grep $(params.CONTEXT) | wc -l` -gt 0 ]
      then
        printf yes | tee $(results.needed.path)
      else
        printf no | tee $(results.needed.path)
      fi
