apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{
      "description": "Build an image from code.",
      "name": "Iter8 pipeline"}'
  name: iter8-pipeline
spec:
  resources:
  - name: source
    type: git
  params:
  - name: CONTEXT
    description: Relative directory path to Dockerfile
  tasks:
  - name: is-build-needed
    taskRef:
      name: is-build-needed
    resources:
      inputs:
      - name: source
        resource: source
    params:
    - name: CONTEXT
      value: $(params.CONTEXT)
  - name: get-commit-id
    taskRef:
      name: get-commit-id
    resources:
      inputs:
      - name: source
        resource: source
    when:
    - input: "$(tasks.is-build-needed.results.needed)"
      operator: in
      values: ["yes"]
  - name: kaniko
    taskRef:
      name: kaniko
    resources:
      inputs:
      - name: source
        resource: source
    params:
    - name: IMAGE
      value: haih/helloworld:$(tasks.get-commit-id.results.commit-id)
    - name: CONTEXT
      value: $(params.CONTEXT)
    when:
    - input: "$(tasks.is-build-needed.results.needed)"
      operator: in
      values: ["yes"]
  - name: start-experiment
    taskRef:
      name: start-experiment
    resources:
      inputs:
      - name: source
        resource: source
    params:
    - name: VERSION
      value: $(tasks.get-commit-id.results.commit-id)
    - name: USER
      value: huang195
    - name: BRANCH
      value: cicd
    - name: GITHUB_TOKEN_SECRET
      value: iter8-token
    when:
    - input: "$(tasks.is-build-needed.results.needed)"
      operator: in
      values: ["yes"]
