# This role enables writing secrets; 
# Iter8 handler uses this role during Helm release tasks
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-reader
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs: ["get", "list"]
---
# Helm v3 uses secrets to store Helm release information.
# 
# By default, when Helm is used within Iter8 experiments, secrets 
# will be located in the default namespace.
#
# This role binding enables Iter8 handler to manipulate secrets in the default namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-handler
  namespace: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: iter8-handlers
  apiGroup: ""
---
