apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    pipelines.kubeflow.org/pipeline_spec: '{
      "description": "Build an image from code.",
      "name": "Iter8 pipeline"}'
  name: iter8-pipeline
spec:
  resources:
  - name: source
    type: git
  params:
  - name: CONTEXT
    description: Relative directory path to Dockerfile
  tasks:
  - name: get-commit-id
    taskRef:
      name: get-commit-id
    resources:
      inputs:
      - name: source
        resource: source
  - name: kaniko
    taskRef:
      name: kaniko
    resources:
      inputs:
      - name: source
        resource: source
    params:
    - name: IMAGE
      value: haih/helloworld:$(tasks.get-commit-id.results.commit-id)
    - name: CONTEXT
      value: $(params.CONTEXT)
