apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: samples/cicd
    repoURL: https://github.com/huang195/iter8
    targetRevision: cicd
  syncPolicy:
    automated:
      prune: true
