apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: networking.istio.io
    jsonPointers:
    - /spec/http/0/route/0/weight
    - /spec/http/0/route/1/weight
    kind: VirtualService
  project: default
  source:
    path: samples/cicd
    repoURL: https://github.com/huang195/iter8
    targetRevision: cicd
  syncPolicy:
    automated:
      prune: true
