apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-app-candidate
  labels:
    app: iter8-app-candidate
    version: fbd590c
    app.kubernetes.io/instance: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-app-candidate
      version: fbd590c
  template:
    metadata:
      labels:
        app: iter8-app-candidate
        version: fbd590c
    spec:
      containers:
      - name: iter8-app-candidate
        image: haih/helloworld:fbd590c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: fbd590c
