apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-app-candidate
  labels:
    app: iter8-app-candidate
    version: v94d8370
    app.kubernetes.io/instance: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-app-candidate
      version: v94d8370
  template:
    metadata:
      labels:
        app: iter8-app-candidate
        version: v94d8370
    spec:
      containers:
      - name: iter8-app-candidate
        image: haih/helloworld:v94d8370
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: v94d8370
