apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-app-candidate
  labels:
    app: iter8-app-candidate
    version: 6e8983d
    app.kubernetes.io/instance: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-app-candidate
      version: 6e8983d
  template:
    metadata:
      labels:
        app: iter8-app-candidate
        version: 6e8983d
    spec:
      containers:
      - name: iter8-app-candidate
        image: haih/helloworld:6e8983d
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: 6e8983d
