apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-app-candidate
  labels:
    app: iter8-app-candidate
    version: v4cda05c
    app.kubernetes.io/instance: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-app-candidate
      version: v4cda05c
  template:
    metadata:
      labels:
        app: iter8-app-candidate
        version: v4cda05c
    spec:
      containers:
      - name: iter8-app-candidate
        image: image-registry.openshift-image-registry.svc:5000/default/helloworld:v4cda05c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: v4cda05c
