apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-app-stable
  labels:
    app: iter8-app-stable
    version: vf4b3977
    app.kubernetes.io/instance: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-app-stable
      version: vf4b3977
  template:
    metadata:
      labels:
        app: iter8-app-stable
        version: vf4b3977
    spec:
      containers:
      - name: iter8-app-stable
        image: haih/helloworld:vf4b3977
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: vf4b3977
