apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-app-stable
  labels:
    app: iter8-app-stable
    version: v03c2f40
    app.kubernetes.io/instance: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-app-stable
      version: v03c2f40
  template:
    metadata:
      labels:
        app: iter8-app-stable
        version: v03c2f40
    spec:
      containers:
      - name: iter8-app-stable
        image: haih/helloworld:v03c2f40
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: v03c2f40
