apiVersion: apps/v1
kind: Deployment
metadata:
  name: iter8-app-stable
  labels:
    app: iter8-app-stable
    version: ve920980
    app.kubernetes.io/instance: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iter8-app-stable
      version: ve920980
  template:
    metadata:
      labels:
        app: iter8-app-stable
        version: ve920980
    spec:
      containers:
      - name: iter8-app-stable
        image: image-registry.openshift-image-registry.svc:5000/default/helloworld:ve920980
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: version
          value: ve920980
