apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: gitops-exp-10414
spec:
  # target identifies the service under experimentation using its fully qualified name
  target: default/productpage
  strategy:
    # this experiment will perform an A/B test
    testingPattern: Canary
    # this experiment will progressively shift traffic to the winning version
    deploymentPattern: Progressive
    actions:
      # when the experiment completes, promote the winning version in the Env repo
      finish:
      - task: notification/http
        with:
          url: https://api.github.com/repos/huang195/iter8/actions/workflows/gitops-finish.yaml/dispatches
          authType: Bearer
          secret: github-token
          body:  |
            {
              "ref":"master",
              "inputs":{
                "basedir": "samples/cicd",
                "filepath": "{{.filepath}}"
              }
            }
          headers:
          - name: Accept
            value: application/vnd.github.v3+json
          method: POST

      - task: common/bash
        with:
          script: |
            kubectl -n {{ .namespace }} apply -f https://raw.githubusercontent.com/huang195/iter8/master/samples/cicd/route.yaml
  criteria:
    objectives: # used for validating versions
    - metric: default/mean-latency
      upperLimit: 300
    - metric: default/error-rate
      upperLimit: "0.01"
    requestCount: default/request-count
  duration: # product of fields determines length of the experiment
    intervalSeconds: 30
    iterationsPerLoop: 3
  versionInfo:
    # information about the app versions used in this experiment
    baseline:
      name: iter8-app-stable
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: deployment.yaml
      weightObjRef:
        apiVersion: route.openshift.io/v1
        kind: Route
        namespace: default
        name: iter8-app-route
        fieldPath: .spec.to.weight
    candidates:
    - name: iter8-app-candidate
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: deployment-candidate.yaml
      weightObjRef:
        apiVersion: route.openshift.io/v1
        kind: Route
        namespace: default
        name: iter8-app-route
        fieldPath: .spec.alternateBackends[0].weight
