##########################################################################################
#
# This replaces gitops/run with image/run, which runs a user-defined image
# Pros: Better defined interface, less prone to human mistakes/attacks, and user has the 
#       flexibility to implement the desired function however he likes (similar to Github Actions)
# Cons: Still a lot of parameters, more user responsibility
#
##########################################################################################
apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: gitops-exp-24489
spec:
  # target identifies the service under experimentation using its fully qualified name
  target: default/productpage
  strategy:
    # this experiment will perform an A/B test
    testingPattern: Canary
    # this experiment will progressively shift traffic to the winning version
    deploymentPattern: Progressive
    actions:
      # when the experiment completes, promote the winning version using kubectl apply
      finish:
      - task: image/run
        with:
          image: user-repo/mygithandler:latest
          env:
            org: iter8-tools
            repo: iter8
            branch: gitops
            user: gitops-demo
            userEmail: iter8@iter8.tools
            userName: Mr. Iter8
            token: iter8-token
            dir: samples/gitops
            stable: productpage.yaml
            candidate: productpage-candidate.yaml
            gitCommitMsg: update baseline
            gitCommitBranch: iter8_exp
            gitPRTitle: Iter8 GitOps
            gitPRBody: Update baseline
  criteria:
    objectives: # used for validating versions
    - metric: default/mean-latency
      upperLimit: 300
    - metric: default/error-rate
      upperLimit: "0.01"
    requestCount: default/request-count
  duration: # product of fields determines length of the experiment
    intervalSeconds: 10
    iterationsPerLoop: 10
  versionInfo:
    # information about the app versions used in this experiment
    baseline:
      name: productpage-stable
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: productpage.yaml
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: default
        name: bookinfo
        fieldPath: .spec.http[0].route[0].weight
    candidates:
    - name: productpage-candidate
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: productpage-candidate.yaml
      weightObjRef:
        apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        namespace: default
        name: bookinfo
        fieldPath: .spec.http[0].route[1].weight
