apiVersion: iter8.tools/v2alpha2
kind: Experiment
metadata:
  name: gitops-exp-
spec:
  # target identifies the service under experimentation using its fully qualified name
  target: default/productpage
  strategy:
    # this experiment will perform an A/B test
    testingPattern: Canary
    # this experiment will progressively shift traffic to the winning version
    deploymentPattern: Progressive
    actions:
      # use built-in metric collector
      start:
      - task: metrics/collect
        with:
          versions: 
          - name: iter8-app-stable
            url: http://iter8-app-stable.default.svc:8000
          - name: iter8-app-candidate
            url: http://iter8-app-candidate.default.svc:8000
      # when the experiment completes, promote the winning version in the Env repo
      finish:
      - task: common/exec
        with:
          cmd: /bin/bash
          args: [ 
                 "-c",
                 "apt-get install -y git jq curl;\
                  REPO=github.com/huang195/iter8;\
                  BRANCH=cicd;\
                  USER=huang195;\
                  TOKEN=`kubectl -n {{ .namespace }} get secret github-token -o json | jq -r .data.token | base64 -d`;\
                  git config --global user.email 'iter8@iter8.tools';\
                  git config --global user.name 'Iter8';\
                  git clone https://${USER}:${TOKEN}@${REPO} --branch=${BRANCH};\
                  cd iter8/samples/cicd;\
                  TMP=`mktemp`;\
                  sed 's/candidate/stable/g' {{ .filepath }} > $TMP;\
                  mv $TMP deployment.yaml;\
                  rm -f deployment-candidate.yaml;\
                  rm -f experiment.yaml;\
                  if [ `git status -s | wc -l` != 0 ];\
                  then \
                    git checkout -b iter8_exp_end;\
                    git commit -a -m 'update baseline';\
                    git push -f origin iter8_exp_end;\
                    curl -u${USER}:${TOKEN} -XPOST https://api.github.com/repos/huang195/iter8/pulls -s -d \"{\\\"head\\\":\\\"iter8_exp_end\\\", \\\"base\\\":\\\"${BRANCH}\\\", \\\"body\\\":\\\"update baseline\\\", \\\"title\\\":\\\"Iter8 GitOps: end of experiment\\\"}\";\
                  fi;\
                  kubectl -n {{ .namespace }} apply -f route.yaml;\
                 "
                ]
  criteria:
    objectives: # used for validating versions
    - metric: iter8-system/mean-latency
      upperLimit: 300
    - metric: iter8-system/error-rate
      upperLimit: "0.01"
    requestCount: iter8-system/request-count
  duration: # product of fields determines length of the experiment
    intervalSeconds: 10
    iterationsPerLoop: 2
  versionInfo:
    # information about the app versions used in this experiment
    baseline:
      name: iter8-app-stable
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: deployment.yaml
      weightObjRef:
        apiVersion: route.openshift.io/v1
        kind: Route
        namespace: default
        name: iter8-app-route
        fieldPath: .spec.to.weight
    candidates:
    - name: iter8-app-candidate
      variables:
      - name: namespace # used by final action if this version is the winner
        value: default
      - name: filepath
        value: deployment-candidate.yaml
      weightObjRef:
        apiVersion: route.openshift.io/v1
        kind: Route
        namespace: default
        name: iter8-app-route
        fieldPath: .spec.alternateBackends[0].weight
